# Generated by Django 3.2 on 2022-05-24 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('description', models.TextField(max_length=512, verbose_name='Описание')),
                ('journal_type', models.CharField(blank=True, choices=[('BULLET', 'Bullet'), ('FOOD', 'Еда'), ('TRAVEL', 'Путешествия'), ('SPORT', 'Спорт')], max_length=255, verbose_name='Тип журнала')),
                ('publisher', models.TextField(blank=True, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Базовый класс литературы',
                'verbose_name_plural': 'Базовые классы литературы',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('description', models.TextField(max_length=512, verbose_name='Описание')),
                ('num_pages', models.IntegerField(default=0, verbose_name='Количество страниц')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='core.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Базовый класс литературы',
                'verbose_name_plural': 'Базовые классы литературы',
                'abstract': False,
            },
        ),
    ]
